Fix release note check

diff --git a/.github/workflows/build-test-all.yml b/.github/workflows/build-test-all.yml
--- a/.github/workflows/build-test-all.yml
+++ b/.github/workflows/build-test-all.yml
@@ -88,8 +88,7 @@ jobs:
     steps:
       - uses: actions/checkout@v1
       - name: Check release notes exist
-        run: |
-          [[ ! -f release_notes/v${GITHUB_REF:11}.md ]] ; && exit 1
+        run: [[ -f release_notes/v${GITHUB_REF:11}.md ]] && echo "Release notes found" || { echo "Release notes not found"; exit 1; }
       - name: Get vhdl_lang linux
         uses: actions/download-artifact@v1
         with:
